spring:
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    hikari:
      minimum-idle: 3
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      connection-test-query: SELECT 1
  transaction:
    rollback-on-commit-failure: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 5MB

mybatis:
  type-aliases-package: com.beatao.provider.model.dto,com.beatao.provider.model.vo
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
